### ISSUE TITLE
Bulk Updating URLs

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#215]
When running the bulk update job for bundle URLs, I get this error:
```
Job execution failed: SQLSTATE[08006] [7] FATAL:  remaining          [error]
connection slots are reserved for non-replication superuser
connections
```
More info:
- 120,324 entities
- `Calling: tripal_update_all(bio_data_6, feature/[data__identifier], alias)`

I am not sure if this is a Tripal issue or Postgres. Anyone know how to get around this?

Thanks!

**Comment by shawnawsu** [comment]
Hi @almasaeed2010 ,

Do you get any other errors in your drupal logs? Do you get the error right away or does the process run for a bit before reporting the error?

Thanks!
Shawna

**Comment by almasaeed2010** [comment]
Hi @shawnawsu 
It runs for about 30-40 minutes before the errors shows up

Thanks!

**Comment by shawnawsu** [comment]
The terminal should have a running count of the number of updated entries, how many did it get through?

**Comment by almasaeed2010** [comment]
That number gets overwritten when the error is printed. I guess it's because the pointer is set back to the beginning of the line

**Comment by almasaeed2010** [comment]
Looking at the code, it seems there is an implementation issue. Please see https://github.com/tripal/tripal/blob/69479178c9272fb5b76a676e1985ecb68e7c3d2f/tripal/includes/tripal.bulk_update.inc#L29 

The code passes $bundle_tokens as a $reset parameter resulting in loading the entire entity instead of just one field.

**Comment by shawnawsu** [comment]
That might be causing a problem on larger update runs.

I've pushed an update to the 7.x-3.x branch. I just don't have a test environment with that many entities, so if you could test I would appreciate it!

Thanks!

**Comment by almasaeed2010** [comment]
Morning @shawnawsu!

I tested the code in 7.x-3.x but it failed since the tripal_load_entity expects field ids rather than tokens. Gave the following errors once started:
```
[site http://default] [TRIPAL WARNING] [TRPENTITY] The URL alias, polypeptide/, already exists for another page. Please ensure the pattern supplied on the <a href="/admin/structure/bio_data/manage/bio_data_14" target="_blank">Polypeptide Edit Page</a> under URL Path options is unique.
array_key_exists() expects parameter 2 to be array, null given       [warning]
tripal.entities.api.inc:1053
```
And repeated for all available entities.

However, even with that issue fixed, the code still fails with a memory leak issue:
```
2017-12-11 18:27:27: Calling: tripal_update_all(bio_data_6, feature/[data__identifier], alias)
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 344064 bytes) in /data/www/html/hardwoods_dev/drupal-7.52/includes/database/database.inc on line 2227

Fatal error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 344064 bytes) in /data/www/html/hardwoods_dev/drupal-7.52/includes/database/database.inc on line 2227
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Allowed memory size of 4294967296 bytes exhausted (tried to
allocate 344064 bytes) in
/data/www/html/hardwoods_dev/drupal-7.52/includes/database/database.inc,
line 2227
```

I am working on a fix by trying to implement chunking and will see how that goes. It takes a while unfortunately know whether it'll work or not. Will keep you posted.

Thanks!

**Comment by shawnawsu** [comment]
So that error is a different error than was initially reported. Was the initial fail also reporting an out of memory error?

**Comment by almasaeed2010** [comment]
It didn't get that far previously. So there was no memory error.

**Comment by shawnawsu** [comment]
Previously it was running 30-40 mins without running out of memory? How long before the memory error this time?

**Comment by almasaeed2010** [comment]
It was running overnight. The last I checked it was running for 2 hours.

**Comment by shawnawsu** [comment]
Can you show me the code you were using because it's not the code I pushed as I didn't push it till this morning :)

I've just pushed an update to get the bulk upload to return only the entity fields required for the update.

**Comment by almasaeed2010** [comment]
I thought since it's the same code but one didn't have the correct loading of fields so the result is the same when it comes to memory usage. The new code however should make a difference since we are loading only the required fields 👍  
Just one observation though, this code block is being run inside the while loop but the tokens are not changing:
```
    $fields = array();
    foreach ($bundle_tokens as $bundle_token) {
      foreach ($bundle_token as $token) {
        $string = str_replace(array('[', ']'), '', $token);
        $field_array = field_info_field($string);
        $fields[] = $field_array['id'];
      }
    }
```

I think it should be fine to obtain the ids before entering the loop.

I appreciate your help! Thanks!

**Comment by shawnawsu** [comment]
Good call, I just moved it outside the while loop. 

Let me know if that changes anything for you.

**Comment by almasaeed2010** [comment]
Testing now. Thanks!

**Comment by almasaeed2010** [comment]
A quick question, any reason for using the Queue here? It takes a very long time to add all items to the queue and since I don't see any definitions for it to allow cron to process it with a callback, I can't figure out why it is there.

Thanks!

**Comment by almasaeed2010** [comment]
Update on the memory issue. The code failed again with the same memory error so I added a line to show how much memory is being use. It turns out the memory usage was growing exponentially due to the static cache. The cached data were not getting removed by the end of each iteration. Therefore, adding `$ec->resetCache()` fixed the issue for us along with removing the Queue entirely.  Another solution would be to set the `$reset_cache` parameter in `tripal_load_entity()` to false to disable caching.

I'll submit a pull request with the changes for your consideration.

Thanks!

**Comment by spficklin** [comment]
I think the problem is related to issue #139 

In this case, the source of the problem is our chado_db_select function.  If anything in the loop uses that function call it could create this problem.

**Comment by almasaeed2010** [comment]
Hi @spficklin 

Thanks for the response!

I agree that `chado_db_select` was causing the max_connections error but there might be a different reason for the memory leak which is caused by the cache issue as mentioned above https://github.com/tripal/tripal/issues/215#issuecomment-351108769

Thanks

**Comment by almasaeed2010** [comment]
This issue was fixed in PAG hackathon
