### ISSUE TITLE
Error Upgrading from Tripal v2.1 to v3.0-rc2

### ISSUE THREAD

**Issue by cguttai5k** [tripal/tripal#275]
* Tripal Version: 3.0-rc2
* Drupal Version: 7.56
* PostgreSQL Version: 9.6.6
* PHP Version: 5.6.32

While I'm upgrading Tripal v2.1 to 3.0, here are the issues I'm facing

Error 1: Enabled "drush pm-enable tripal" 

`php: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_bundle" does not exist`

Error 2:  After enabling tripal_chado module  

exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_jobs_job_id_idx" does not exist' in /includes/database/database.inc:2227

Any ideas or suggestions? Thanks!

**Comment by bradfordcondon** [comment]
Hello!
Are you following the instructions at [tripal.info?](http://tripal.info/tutorials/v3.x/upgrade/2.x-to-3.x)  
My first guess would be that you did not disable core before installing the new tripal.
```
drush pm-disable tripal_core
 drush pm-enable tripal
#...etc
```

edit: I see that this isnt your first time upgrading a site so that seems unlikely... maybe there is an issue with the rc2 release?  Let me see if i have the same issue.

**Comment by cguttai5k** [comment]
@bradfordcondon thanks for responding.... Yes I'm following instructions, disabled tripal core, deleted old Tripal v2 module directories and downloaded new version then enabled tripal, tripal_chado.

Previously when I tested version upgrade it did worked with some interruptions but not sure why I'm having trouble now. Thanks!

**Comment by bradfordcondon** [comment]
hi @cguttai5k .  I made a fresh instance coming from Tripal 2 and successfully installed Tripal 3.0-rc2.

Your error is indicating that some of the tables installed in the basic `tripal` module were not created.  I'm not sure why this would happen.  Can you try `drush dre tripal`, which will disable, uninstall, and reinstall tripal?   We want to not see a `php: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "tripal_bundle" does not exist` error.

**Comment by cguttai5k** [comment]
thanks @bradfordcondon, `drush pm-enable tripal` enabled successfully.

after running `drush pm-enable tripal_chado` :

 ![image](https://user-images.githubusercontent.com/24276916/35658845-473d8cd2-06d1-11e8-859c-946b15476cb3.png)

**Comment by spficklin** [comment]
Hi @cguttai5k 

I think the problem is that somehow you must have had an index that was accidentally dropped or renamed on that tripal_jobs table, and now Tripal is having issues because of it during the upgrade.  I just committed some code changes that may help.   Can you pull the most recent development code and try again?

**Comment by cguttai5k** [comment]
Hi thanks @spficklin, that did not worked for me, and when I try enabling tripal_chado I'm also getting this again:

```
Drush command terminated abnormally due to an unrecoverable error.                                              [error]
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_bundle" does not exist
LINE 3: tripal_bundle tb
        ^: SELECT tb.*
FROM 
{tripal_bundle} tb; Array
(
)
 in tripal_entity_info_alter() (line 240 of /sites/all/modules/contrib/tripal/tripal/includes/tripal.entity.inc)
```

**Comment by spficklin** [comment]
So, let's look at each problem separately.   First is the one with the missing index.  When you enabled the tripal module did you still get that same message?

**Comment by cguttai5k** [comment]
yes Stephen, I'm still getting that same index error when I enable "tripal_chado".

Edit:

sorry that was resolved and now error had changed to duplicate table @spficklin :

`exception 'PDOException' with message 'SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "tripal_token_formats_type_application_key" already exists' in /includes/database/database.inc:2227                   [error]
`

**Comment by spficklin** [comment]
Did you start the upgrade process from the beginning or restart it from where you left off?

**Comment by cguttai5k** [comment]
Again i started updating tripal process with the development version,

1. Successfully disabled tripal core.

   (Here is the step which mislead me to continue going further & enabling 'tripal_chado').

2. when I try to enable tripal "drush pm-enable tripal" I got two messages saying that tripal is already enabled and at the same time saying that there was problem enabling tripal.


```
$ drush pm-enable tripal
tripal is already enabled.                                           [ok]
The following extensions will be enabled: tripal
Do you really want to continue? (y/n): y
tripal was enabled successfully.                                     [ok]
There was a problem enabling tripal.                                 [error]

```

I thought of going to the /admin/modules interface and see whether tripal is enabled or not but as expected tripal is not enabled, I tried enabling it using admin interface immediately site is completely down.

now again I tried enabling tripal using drush it was throwing the below error:

```
$ drush pm-enable tripal
WD php: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:     [error]
relation "tripal_bundle" does not exist
LINE 3: tripal_bundle tb
        ^: SELECT tb.*
FROM 
{tripal_bundle} tb; Array
(
)
 in tripal_entity_info_alter() (line 263 of
/sites/all/modules/contrib/tripal/tripal/includes/tripal.entity.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_bundle" does not exist
LINE 3: tripal_bundle tb
        ^: SELECT tb.*
FROM 
{tripal_bundle} tb; Array
(
)
 in tripal_entity_info_alter() (line 263 of /sites/all/modules/contrib/tripal/tripal/includes/tripal.entity.inc).
```

thanks again for all your help. @spficklin

**Comment by cguttai5k** [comment]
The above issue got fixed, sincerely thank you for your time @spficklin & @isumoc now I'm at the step where preparing the chado and launch job.

while I'm doing this I had an issue :

```
$ drush trp-run-jobs --username=administrator --root=/var/www/html
2018-02-13 17:36:31
Tripal Job Launcher
Running as user 
-------------------
2018-02-13 17:36:31: There are 3 jobs queued.
2018-02-13 17:36:31: Calling: tripal_tripal_cron_notification()
Invalid argument supplied for foreach() TripalJob.inc:257                                                                                         [warning]
2018-02-13 17:36:31: Calling: tripal_expire_collections()
Invalid argument supplied for foreach() TripalJob.inc:257                                                                                         [warning]
2018-02-13 17:36:31: Calling: tripal_chado_prepare_chado()
Creating Tripal Materialized Views and Custom Tables...
Loading Ontologies...
Ontology already loaded (skipping): Taxonomic Rank...
Loading ontology: Tripal Contact (28)...
Ontology already loaded (skipping): Tripal Publication...
Ontology already loaded (skipping): Sequence Ontology...
Populating materialized view db2cv_mview...
Done.
Populating materialized view cv_root_mview...
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 7 no connection to the server' in /includes/database/database.inc:1092
Stack trace:
#0 /includes/database/database.inc(1092): PDO->rollBack()
#1 /includes/database/database.inc(1989): DatabaseConnection->rollback('drupal_transact...')
#2 /sites/all/modules/contrib/tripal/tripal_chado/api/tripal_chado.mviews.api.inc(383): DatabaseTransaction->rollback()
#3 /sites/all/modules/contrib/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(215): tripal_populate_mview('1')
#4 [internal function]: tripal_chado_prepare_chado(Object(TripalJob))
#5 /sites/all/modules/contrib/tripal/tripal/includes/TripalJob.inc(292): call_user_func_array('tripal_chado_pr...', Array)
#6 /sites/all/modules/contrib/tripal/tripal/api/tripal.jobs.api.inc(417): TripalJob->run()
#7 /sites/all/modules/contrib/tripal/tripal/tripal.drush.inc(232): tripal_launch_job(0, NULL, -1, 0)
#8 [internal function]: drush_tripal_trp_run_jobs()
#9 phar:///bin/drush/includes/command.inc(422): call_user_func_array('drush_tripal_tr...', Array)
#10 phar:///bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#11 [internal function]: drush_command()
#12 phar:///bin/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#13 phar:///bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#14 phar:///bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 phar:///bin/drush/includes/startup.inc(458): drush_main()
#16 phar:///bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#17 phar:///bin/drush/drush(114): drush_startup(Array)
#18 /bin/drush(10): require('phar:///app/loc...')
#19 {main}
SQLSTATE[HY000]: General error: 7 no connection to the server
WD tripal_job: SQLSTATE[HY000]: General error: 7 no connection to the server                                                                      [error]
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[HY000]: General error: 7 no connection to the server
SQLSTATE[HY000]: General error: 7 no connection to the server                                                                                     [error]
Custom table, 'contactprop' , already exists. Table structure not changed, but definition array has been saved.                                   [status]
Custom table, 'featuremap_dbxref' , already exists. Table structure not changed, but definition array has been saved.                             [status]
Custom table, 'featuremapprop' , already exists. Table structure not changed, but definition array has been saved.                                [status]
Custom table, 'featureposprop' , already exists. Table structure not changed, but definition array has been saved.                                [status]
Custom table, 'pubauthor_contact' , already exists. Table structure not changed, but definition array has been saved.                             [status]
Custom table, 'tripal_gff_temp' , already exists. Table structure not changed, but definition array has been saved.                               [status]
Custom table, 'tripal_gffcds_temp' , already exists. Table structure not changed, but definition array has been saved.                            [status]
Custom table, 'tripal_gffprotein_temp' , already exists. Table structure not changed, but definition array has been saved.                        [status]
Materialized view, organism_stock_count, already exists. Skipping creation.                                                                       [status]
Materialized view, library_feature_count, already exists. Skipping creation.                                                                      [status]
Materialized view, organism_feature_count, already exists. Skipping creation.                                                                     [status]
Materialized view, analysis_organism, already exists. Skipping creation.                                                                          [status]
Materialized view, cv_root_mview, already exists. Skipping creation.                                                                              [status]
Materialized view, db2cv_mview, already exists. Skipping creation.                                                                                [status]
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 7 no connection to the server' in /includes/database/database.inc:2227
Stack trace:
#0 /includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /includes/database/database.inc(2406): DatabaseConnection_pgsql->query('SELECT expire, ...', Array, Array)
#3 /includes/lock.inc(167): db_query('SELECT expire, ...', Array)
#4 /includes/lock.inc(146): lock_may_be_available('schema:runtime:...')
#5 /includes/bootstrap.inc(438): lock_acquire('schema:runtime:...')
#6 /includes/bootstrap.inc(460): DrupalCacheArray->set(Array)
#7 [internal function]: DrupalCacheArray->__destruct()
#8 {main}
  thrown in /includes/database/database.inc on line 2227
```

Any thoughts or suggestions??

**Comment by spficklin** [comment]
I'm glad that pull request fixed that issue for your. This new one is a bit puzzling.  The error message states:

> exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 7 no connection to the server' in /includes/database/database.inc:1092

I've not seen this before.  Can you describe your setup?  Is your database server local to your web server?  Were there any network outages during the time you ran the upgrade?

**Comment by cguttai5k** [comment]
Both project code and database are on the same server, as far as I know there is no network outages or fluctuations during this process.

**Comment by spficklin** [comment]
I think your PostgreSQL server may have had issues during the upgrade.  Do you have any PostgreSQL logs that can help indicate what the problem might be?

**Comment by cguttai5k** [comment]
Sure, here is the information I was able to collect from our db admin :

Reviewing the postgresql logs this appears to have started on 2/8/2018.  It's a loop where the postmaster kills the postgresql process attempting to execute a statement:

>  Failed process was running: DELETE FROM search_total
>  WHERE ( (word = '0') OR (word = '103472') OR (word = '105852') OR (word = '113894') OR (word = '11894') OR (word = '1214') OR (word = '121845refdiacipsyllidgenomeassemblyversion11chrunf') OR (word = '121845refdiacipsyllidgenomeassemblyversion11chrunm') OR (word = '13953') OR (word = '139969') OR (word = '15080') OR (word = '15797') OR (word = '164137') OR (word = '172972') OR (word = '18242') OR (word = '1genome') OR (word = '1st') OR (word = '22035') OR (word = '24777') OR (word = '260904') OR (word = '260904jpg') OR (word = '260934') OR (word = '260934jpg') OR (word = '27457refasm78921v2chrunfagapsbigwiggz') OR (word = '27457refasm78921v2chrunfagcbigwiggz') OR (word = '27457refasm78921v2chrunfagz') OR (word = '28588refasm80634v1chrunfagapsbigwiggz') OR (word = '28588refasm80634v1chrunfagcbigwiggz') OR (word = '28588refasm80634v1chrunfagz') OR (word = '2nd') OR (word = '2official') OR (word = '3additional') OR (word = '3dayoldembryornaseq') OR (word = '4tran
 s
>   criptome
>      s') OR (word =
>
>   On restart the following is output to the log:
>
>     2018-02-10 00:26:18.931 EST >LOG:  redo starts at 1FE/1A55CEB0
>        < 2018-02-10 00:26:18.967 EST >LOG:  invalid record length at 1FE/1A62A138: wanted 24, got 0
>        < 2018-02-10 00:26:18.967 EST >LOG:  redo done at 1FE/1A62A110
>

**Comment by spficklin** [comment]
It seems to be clearing out your search_total table and causing problems. This seems related to issue #276.  Can you test the following to see if it fixes it.  Prior to the migration can you run these SQL commands:

```
db_query('TRUNCATE {search_total}')
db_query('TRUNCATE {search_index}')
```

That should clear out your site indexes.  You can then restart the indexing process at /admin/config/search/settings.  

If that solves the problem for you then it seems we need to do something in the upgrade process for sites that are using Drupal's search indexing.

**Comment by cguttai5k** [comment]
that idea actually worked @spficklin I was able to get through it but with one duplicate record (chado_insert_record) insertion failed into cvterm table, here is the brief copy of that: 

```
Creating Tripal Materialized Views and Custom Tables...
Loading Ontologies...
Ontology already loaded (skipping): Taxonomic Rank...
Loading ontology: Tripal Contact (28)...
Ontology already loaded (skipping): Tripal Publication...
Ontology already loaded (skipping): Sequence Ontology...
Populating materialized view db2cv_mview...
Done.
Populating materialized view cv_root_mview...
Done.
Making semantic connections for Chado tables/fields...

WD tripal_chado: chado_insert_record; Cannot insert duplicate record into cvterm table: Array                                                     [error]
(
    [cv_id] => 23
    [name] => Analysis Type
    [definition] => The type of analysis that was performed.
    [dbxref_id] => 260795
    [is_obsolete] => 0
    [is_relationshiptype] => 0
)

ERROR (TRIPAL_CHADO): chado_insert_record; Cannot insert duplicate record into cvterm table: Array
(
    [cv_id] => 23
    [name] => Analysis Type
    [definition] => The type of analysis that was performed.
    [dbxref_id] => 260795
    [is_obsolete] => 0
    [is_relationshiptype] => 0
)

[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_insert_record; Cannot insert duplicate record into cvterm table: Array(    [cv_id] => 23    [name] => Analysis Type    [definition] => The type of analysis that was performed.    [dbxref_id] => 260795    [is_obsolete] => 0    [is_relationshiptype] => 0)
WD tripal_cv: Failed to insert the term: Analysis Type (local)                                                                                    [warning]
[site http://default] [TRIPAL WARNING] [TRIPAL_CV] Failed to insert the term: Analysis Type (local)
Map Chado Controlled vocabularies to Tripal Terms...

Done.
Creating common Tripal Content Types...

NOTE: Loading of publications is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
insertions/updates is rolled back and will not be found in the database

Processing 1 of 1. Memory usage: 108,367,480 bytes.
Syncing publications with Drupal...

Sync'ing pub records.

1 pub records found.

NOTE: Syncing is performed using a database transaction.
If the sync fails or is terminated prematurely then the entire set of
synced items is rolled back and will not be found in the database


Complete!
2018-02-16 10:55:59: Calling: tripal_tripal_cron_notification()
Invalid argument supplied for foreach() TripalJob.inc:257                                                                                         [warning]
2018-02-16 10:56:02: Calling: tripal_expire_collections()
Invalid argument supplied for foreach() TripalJob.inc:257                                                                                         [warning]
Custom table, 'contactprop' , already exists. Table structure not changed, but definition array has been saved.                                   [status]
Custom table, 'featuremap_dbxref' , already exists. Table structure not changed, but definition array has been saved.                             [status]
Custom table, 'featuremapprop' , already exists. Table structure not changed, but definition array has been saved.                                [status]
Custom table, 'featureposprop' , already exists. Table structure not changed, but definition array has been saved.                                [status]
Custom table, 'pubauthor_contact' , already exists. Table structure not changed, but definition array has been saved.                             [status]
Custom table, 'tripal_gff_temp' , already exists. Table structure not changed, but definition array has been saved.                               [status]
Custom table, 'tripal_gffcds_temp' , already exists. Table structure not changed, but definition array has been saved.                            [status]
Custom table, 'tripal_gffprotein_temp' , already exists. Table structure not changed, but definition array has been saved.                        [status]
Materialized view, organism_stock_count, already exists. Skipping creation.                                                                       [status]
Materialized view, library_feature_count, already exists. Skipping creation.                                                                      [status]
Materialized view, organism_feature_count, already exists. Skipping creation.                                                                     [status]
Materialized view, analysis_organism, already exists. Skipping creation.                                                                          [status]
Materialized view, cv_root_mview, already exists. Skipping creation.                                                                              [status]
Materialized view, db2cv_mview, already exists. Skipping creation.                                                                                [status]
```

and Stephen there is also a couple of warning messages while I'm running tripal jobs every time:

`Invalid argument supplied for foreach() TripalJob.inc:257                                                                                         [warning]`

Thanks!
