### ISSUE TITLE
GFF3 importer: discontinuous features

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#52]
This issue is being copied over from the Drupal issue queue:  https://www.drupal.org/node/2796857

The GFF3 spec has a section describing discontinuous features which allows a feature to have the same ID and span multiple district regions. This is not supported by the Chado Perl based loader and it's not directly supported by Chado either. However if we want to fully handle the GFF3 spec we should probably consider supporting them. One idea may be to add an option that the user loading the file would have to check that gives their consent to have the Id's renamed automatically for discontinuous features. But if the parent is not specified then a new parent feature may need to be created. It seems Maker may generate CDS feature in this way but a parent is provided. For these we could just rename the IDs.

**Comment by laceysanderson** [comment]
Was this fixed by #268/#274?

**Comment by bradfordcondon** [comment]
looks to me like the issue of the CDS being constructed correctly is resolved.  But this issue might be rephrased as "Do we need to break up CDS into multiple features".

It looks to me like the solution of using multiple featurelocs to describe a discontinuous CDS is already whats done.    And it makes sense to me, because the GFF doesnt assign multiple IDs to the CDS.  Its a single CDS id, in multiple places.  


So, IMO the currently implemented solution is OK, but I definitely want to hear from others more invested in GFF-> Chado.

**Comment by spficklin** [comment]
A discontinuous feature, in my understanding, is an alternative way to represent a feature with multiple "regions" but without specifying the parent attributes. Instead it relies on using the same ID for all of the distinct rows. So, this is indeed a different issue from #268/#274, and we still do not currently handle it in the GFF3 importer.  According to the note in the post above, Maker does utilize this sort of thing and a lot of folks use Maker to predict gene annotations so it would be a good idea to try and support this if Maker still uses it.

**Comment by spficklin** [comment]
For many years this issue has sat in the queue and no one has ever asked for it.  So, I'm marking it for "Maybe Later" and closing it out.
