### ISSUE TITLE
request: support field permissions module in web services

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#749]
## Feature Request/Discussion

Background #742 

I wrote a guide demonstrating field-level permissions implemented ia the drupal field_permissions module, but web services dont support them.  If you make a field admin only, two things happen:
* admin only fields show up in web service requests
* You get this warning:

```
Notice: Undefined offset: 0 in TripalContentService_v0_1->addEntityField() (line 383 of /Users/bc/tripal/sites/all/modules/tripal/tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc).
```

## resolution
At first glance, looks easy to resolve the warning by adding this to the web services class just prior to here: 

https://github.com/tripal/tripal/blob/bfca9765a5ef7aece7b4355c886d91513a89cadb/tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc#L383

```php
  if (empty($values)){
        return;
      }

      // If the value is an array and this is the field page then all of those
      // key/value pairs should be added directly to the response.
      if (is_array($values[0])) {
```

adding this also causes the ws to work how i'd expect: it isnt returned since we didnt have the permission enabled for an anonymous user.

probably also need to add a case for where cardinality != 1....  what do you think?  This would make the ws behave how i expect (field isnt shown on web services), and it resolves the php warning.

**Comment by bradfordcondon** [comment]
@bradfordcondon will make the pr and explicitly ask @spficklin

**Comment by bradfordcondon** [comment]
doing as i suggest above resolves the warning, but the content still appears...

https://github.com/tripal/tripal/tree/749_webservices_field_permission

ah ok, but there is a field_permission key.  it has a tpe value, but i think just retruning if the key is set at all is good enough?

**Comment by spficklin** [comment]
I think this is now resolved with the PR.  Closing but if not please reopen.

**Comment by bradfordcondon** [comment]
I thought of an edge case i want to test before i close this issue.

if field permissions are set for editing, but anonymous users are allowed to view the field, will it show up in web services?

**Comment by bradfordcondon** [comment]
unfortunately i've confirmed my fix was too simplistic.
if we set custom permissions allowing admins to set the value, but anyone to view it....
![screen shot 2018-12-18 at 5 42 29 pm](https://user-images.githubusercontent.com/7063154/50187540-5437ef00-02ec-11e9-8050-3003d358977b.png)


The field will appear on the content page, but not on web services: we exclude it because the field permission is 2.

Instead we need to review the custom permission and check if anonymous users have permission to view the value.

**Comment by bradfordcondon** [comment]
@spficklin what is hte permission level of web services?
The below snippet works as intended assuming web services should have permissions of an anonymous user.
Or does web services have a user account, and i should use `$global user` ?

```php
 if (isset($field['field_permissions']['type'])) {

      if ($field['field_permissions']['type'] === '1') {
        // Field is private.
        return;
      }

      if ($field['field_permissions']['type'] === '2') {
        // Field is custom permissions: Check
        // if user has access to view this field in any entity.
        if (!user_access('view ' . $field_name, drupal_anonymous_user())) {
          return;
        }
      }
    }
```

**Comment by bradfordcondon** [comment]
looks like there is a `$user` for web services?  I get access denied incognito, and user reporting as admin otherwise.

So im still not positive thats correct: something using web services will have a drupal account on the local site, and we want to check the permission of that account?

**Comment by bradfordcondon** [comment]
merged, thanks for the reviews all.
